export const ORGANIZE_COPY = {
  explorerRoot: 'Início',
  explorerBack: 'Voltar',
  explorerFoldersLabel: 'Pastas',
  explorerChatsLabel: 'Conversas',
  explorerLooseChatsLabel: 'Conversas soltas',
  explorerChatsInFolderLabel: 'Conversas nesta pasta',
  explorerLooseChatsHint: 'Fora de qualquer pasta',
  explorerAddFolder: 'Nova pasta',
  explorerAddSubfolder: 'Nova subpasta',
  explorerFolderEmpty: 'Vazia',
  explorerChatCountOne: '1 conversa',
  explorerChatCountMany: '{count} conversas',
  explorerFolderCountOne: '1 pasta',
  explorerFolderCountMany: '{count} pastas',
  explorerEmptyFolder: 'Esta pasta está vazia',
  explorerEmptyFolderHint: 'Crie uma conversa ou subpasta.',
  explorerPinnedLabel: 'Fixas',
  rename: 'Renomear',
  moveTo: 'Mover para…',
  pin: 'Fixar',
  unpin: 'Desafixar',
  delete: 'Apagar',
  select: 'Selecionar',
  noCollection: 'Sem pasta',
  folderRename: 'Renomear pasta',
  folderDelete: 'Apagar pasta',
  folderDeleteConfirm: 'Apagar «{name}»? As conversas voltam ao nível acima.',
  folderNamePlaceholder: 'Nome da pasta',
  conversationNamePlaceholder: 'Nome da conversa',
  save: 'Salvar',
  cancel: 'Cancelar',
  moveTitle: 'Mover conversa',
  createFolderTitle: 'Nova pasta',
  renameFolderTitle: 'Renomear pasta',
  renameConversationTitle: 'Renomear conversa',
  menuAria: 'Opções da conversa',
  folderMenuAria: 'Opções da pasta',
  dragAria: 'Arrastar conversa',
  dragHint: 'Arraste para mover entre pastas',
  dragDropHint: 'Solte aqui',
} as const;
